/**
 * ============================================
 * INREAD SCROLL CONTROLLER (FRAMEWORK)
 * ============================================
 *
 * This file contains the scroll controller logic for InRead Scroll creatives.
 * DO NOT EDIT this file - define animation in animation.js
 */

// ============================================
// CORE CONTROLLER DEFINITION
// ============================================

window.RtbhInPageAd = function (config) {
  // Fallback: if outerHeight is not provided, use height
  if (config.outerHeight === undefined || config.outerHeight === null) {
    config.outerHeight = config.height;
  }

  var lastViewportPercent = 90;
  var tl = null;

  // Animation visibility thresholds (0-100)
  var animationStartThreshold = config.animationStartThreshold || 100;
  var animationEndThreshold = config.animationEndThreshold || -50;

  var settings = {
    isEligibleForClipFeature: false,
    isEligibleForViewPortScrollFeature: false,
  };

  // ============================================
  // HELPER FUNCTIONS
  // ============================================

  function syncTimelineWithPosition(viewportPercent) {
    if (viewportPercent == null) {
      return 0;
    }

    if (tl === null) {
      lastViewportPercent = viewportPercent;
      return 0;
    }

    // Map viewportPercent to animation progress based on thresholds
    var progress;

    if (viewportPercent >= animationStartThreshold) {
      progress = 0;
    } else if (viewportPercent <= animationEndThreshold) {
      progress = 1;
    } else {
      progress =
        (animationStartThreshold - viewportPercent) /
        (animationStartThreshold - animationEndThreshold);
    }

    // Clamp
    if (progress < 0) progress = 0;
    if (progress > 1) progress = 1;

    // Set GSAP timeline progress
    tl.pause().progress(progress);

    lastViewportPercent = viewportPercent;

    return progress;
  }

  function initBanner() {
    var els = document.querySelectorAll('[data-action="banner"]');

    for (var i = 0; i < els.length; i++) {
      var el = els[i];

      if (el.classList) {
        el.classList.remove("hide");
      } else {
        var classes = el.className.split(" ");
        for (var j = classes.length - 1; j >= 0; j--) {
          if (classes[j] === "hide") {
            classes.splice(j, 1);
          }
        }
        el.className = classes.join(" ");
      }

      el.style.display = "";
    }
  }

  function initImages() {
    var imgs = document.querySelectorAll("img[data-img_src]");

    for (var i = 0; i < imgs.length; i++) {
      var img = imgs[i];
      var dataSrc = img.getAttribute("data-img_src");

      if (dataSrc) {
        img.setAttribute("src", dataSrc);
      }

      img.removeAttribute("data-img_src");
    }
  }

  function recalculateLayer(
    topWindow,
    inReadRootNode,
    iframeAdNode,
    insTagNode,
  ) {
    var rootNode = document.querySelector('[data-item="inread-root"]');
    var contentNode = document.querySelector('[data-item="inread-content"]');

    if (
      !settings.isEligibleForViewPortScrollFeature ||
      !topWindow ||
      !iframeAdNode ||
      !insTagNode
    ) {
      return;
    }

    rootNode.style.width = config.width + "px";
    rootNode.style.height = config.outerHeight + "px";

    contentNode.style.height = config.outerHeight + "px";
  }

  function handleOnCleanup() {
    if (!settings.isEligibleForClipFeature) {
      return;
    }

    var rootNode = document.querySelector('[data-item="inread-root"]');
    var contentNode = document.querySelector('[data-item="inread-content"]');

    rootNode.style.width = config.width + "px";
    rootNode.style.height = config.height + "px";

    contentNode.style.height = config.height + "px";
  }

  // ============================================
  // CALLBACK HANDLERS
  // ============================================

  function onInitCallback(
    topWindow,
    inReadRootNode,
    iframeAdNode,
    insTagNode,
    featuresSupport,
  ) {
    settings.isEligibleForClipFeature =
      featuresSupport.isEligibleForClipFeature;
    settings.isEligibleForViewPortScrollFeature =
      featuresSupport.isEligibleForViewPortScrollFeature;

    // Initialize
    initImages();
    initBanner();

    // Initialize animation from external file (animation.js)
    if (typeof window.initAnimation === "function") {
      tl = window.initAnimation();
      window.tl = tl; // expose for debugging
    }

    recalculateLayer(topWindow, inReadRootNode, iframeAdNode, insTagNode);

    // If viewport scroll feature is not active, play the animation timeline
    if (!settings.isEligibleForViewPortScrollFeature) {
      if (tl) {
        tl.play();
      }
    } else {
      syncTimelineWithPosition(lastViewportPercent);
    }

    // Cleanup on page unload
    window.addEventListener("pagehide", handleOnCleanup);
    window.addEventListener("beforeunload", handleOnCleanup);
  }

  function onResizeCallback(
    topWindow,
    inReadRootNode,
    iframeAdNode,
    insTagNode,
  ) {
    recalculateLayer(topWindow, inReadRootNode, iframeAdNode, insTagNode);
  }

  function onViewportScrollCallback(viewportInfo) {
    syncTimelineWithPosition(viewportInfo.percent);
  }

  // ============================================
  // CLICK HANDLER SETUP
  // ============================================

  function onReady() {
    document.querySelectorAll('[data-action="click"]').forEach(function (el) {
      RtbhEnabler.addClickEvent(el, function () {
        RtbhEnabler.open(window.clickTag, "defaultClickTag");
      });
    });
  }

  RtbhEnabler.onDocumentReady(onReady);

  // ============================================
  // PUBLIC API
  // ============================================

  return {
    onInitCallback: onInitCallback,
    onResizeCallback: onResizeCallback,
    onViewportScrollCallback: onViewportScrollCallback,
  };
};

// ============================================
// UTILITY FUNCTIONS
// ============================================

function detectCreativeSize(configs) {
  if (!Array.isArray(configs)) {
    return configs || { width: 300, height: 250 };
  }

  // Ad Turbo replacing size. Fallback window size
  var width = isNaN("__CREATIVE_WIDTH__")
    ? window.innerWidth
    : parseInt("__CREATIVE_WIDTH__", 10);
  var height = isNaN("__CREATIVE_HEIGHT__")
    ? window.innerHeight
    : parseInt("__CREATIVE_HEIGHT__", 10);

  // Find matching config
  var config = configs.find(function (c) {
    return c.width === width && c.height === height;
  });

  return config || configs[0]; // fallback to first config
}

function applyConfigStyles(config) {
  var inreadRoot = document.querySelector(".inread-root");
  var banner = document.querySelector(".banner");

  if (inreadRoot) {
    inreadRoot.style.width = config.width + "px";
    inreadRoot.style.height = config.height + "px";
  }

  if (banner) {
    banner.style.width = config.width + "px";
    banner.style.height = config.height + "px";
  }

  // Add size class to body (responsive template convention)
  document.body.classList.add("b" + config.width + "x" + config.height);
}

// ============================================
// AUTO-INITIALIZATION LOGIC
// ============================================

(function () {
  "use strict";

  function initializeCreative() {
    // Get configuration
    var configs = window.creativeConfig;
    var settings = window.creativeSettings || {
      viewportScrollOffsetRatio: 0.5,
      feature: {
        enableClip: false,
        enableViewportScroll: true,
      },
    };

    // Detect current size
    var config = detectCreativeSize(configs);

    // Fallback: if outerHeight is not provided, use height
    if (config.outerHeight === undefined || config.outerHeight === null) {
      config.outerHeight = config.height;
    }

    // Apply dynamic styles from config
    applyConfigStyles(config);

    // Initialize InPage Ad controller
    var RtbhInPageAdInstance = window.RtbhInPageAd(config);

    window.RtbhInPageCotroller(
      config,
      settings,
      RtbhInPageAdInstance.onInitCallback,
      RtbhInPageAdInstance.onResizeCallback,
      RtbhInPageAdInstance.onViewportScrollCallback,
    );
  }

  // Run when DOM is ready
  if (document.readyState === "loading") {
    document.addEventListener("DOMContentLoaded", initializeCreative);
  } else {
    initializeCreative();
  }
})();
